# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getlastn < Formula
  desc ""
  homepage "https://github.com/dinglevin/levin-pub-tools/getlastn"
  version "0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.7/levin-pub-tools_0.7_darwin_amd64.tar.gz"
      sha256 "3b1513f5d4d17e8217868834566b8b83ec315bda3d6cb8f3f02965c6f596016a"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.7/levin-pub-tools_0.7_darwin_arm64.tar.gz"
      sha256 "30a405bacfc260f1e76c938d3216bec4fee192ae2960be4bdecf0b0f5685fc77"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.7/levin-pub-tools_0.7_linux_amd64.tar.gz"
      sha256 "8a6bcf9551262e41d0104c2eab6342247064c7592d8ff04132e5262d63510156"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.7/levin-pub-tools_0.7_linux_arm64.tar.gz"
      sha256 "903d3727620091eeca7837e01323102c08334163a6f4fbe4bcd26abed629b524"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end
end
