# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getlastn < Formula
  desc ""
  homepage "https://github.com/dinglevin/levin-pub-tools/getlastn"
  version "0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.6/levin-pub-tools_0.6_darwin_arm64.tar.gz"
      sha256 "a1c42e1c02d01d28cc9385291e93f65ee481bf075f4d92a78181b548de307349"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.6/levin-pub-tools_0.6_darwin_amd64.tar.gz"
      sha256 "c4146dcf9c4408db3a0d0365fa87e653b766590d1fcc51485da711bfcee2ebd8"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.6/levin-pub-tools_0.6_linux_amd64.tar.gz"
      sha256 "30ad5505da967c05e53e2a310396ab8d40b98f8a0c00ad5d4a03868406bfa8e5"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.6/levin-pub-tools_0.6_linux_arm64.tar.gz"
      sha256 "3b2be9a464bac73dbecc746f47496a4c0162df28af738af92cc0ce7f246b3cc8"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end
end
