# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LevinPubTools < Formula
  desc ""
  homepage "https://github.com/dinglevin/levin-pub-tools"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v1.0/levin-pub-tools_1.0_darwin_arm64.tar.gz"
      sha256 "82cd9560b381a7bd145522132549628275419e28f8efeb09ba5bd54b9f8f0083"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v1.0/levin-pub-tools_1.0_darwin_amd64.tar.gz"
      sha256 "4e2f2762e70342ce05d62e882c17546e9edbc2fdca2ff24fceeaf9b7d0ded3d0"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v1.0/levin-pub-tools_1.0_linux_amd64.tar.gz"
      sha256 "1df3678dac4990256e9a6f77331d6ed982dd8bd536ceb669dd4d3ad8c9e16346"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v1.0/levin-pub-tools_1.0_linux_arm64.tar.gz"
      sha256 "7804a76204a1dd51ddfa26d49e60871428950e2ebaea0156bd4a56f2c4d0942e"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end
end
