# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LevinPubTools < Formula
  desc ""
  homepage "https://github.com/dinglevin/levin-pub-tools"
  version "0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.8/levin-pub-tools_0.8_darwin_amd64.tar.gz"
      sha256 "93aa3db787eadf2a11a635a3aae3e3a2a9c67b68447b9bb4c47c05cbd62bf870"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.8/levin-pub-tools_0.8_darwin_arm64.tar.gz"
      sha256 "9cc16a9e38fa595feddbc53ef3800879cf87c900b81563297b84c385192459a7"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.8/levin-pub-tools_0.8_linux_amd64.tar.gz"
      sha256 "53fb0ad5100bd49ceb4bff0bbb9e500e6c69c5c4c2c62d20c8f5a7ab93c3a6c2"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.8/levin-pub-tools_0.8_linux_arm64.tar.gz"
      sha256 "63da8b906571193ae5af45b35733974cb09b8c5ced9181213364ca479205959f"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end
end
