# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LevinPubTools < Formula
  desc ""
  homepage "https://github.com/dinglevin/levin-pub-tools"
  version "0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.9/levin-pub-tools_0.9_darwin_amd64.tar.gz"
      sha256 "22241ae54700f12a92c9517367b6034c39e0ab0c61ccedfafc2e1f2e3cb7044c"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.9/levin-pub-tools_0.9_darwin_arm64.tar.gz"
      sha256 "9e9e2e860bd04bc6930c5498b210a67c8117b1ff8212e3d611c06dba19b1491c"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.9/levin-pub-tools_0.9_linux_amd64.tar.gz"
      sha256 "990c69fe3c54649939e79108b709788691af9e1b588677b1fd27547361ecbc15"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinglevin/levin-pub-tools/releases/download/v0.9/levin-pub-tools_0.9_linux_arm64.tar.gz"
      sha256 "4c4e2c2ec29206340419203d523a652e4e0e25643714b23bb94985ad3019f16a"

      def install
        bin.install "appendstr"
        bin.install "getlastn"
      end
    end
  end
end
